In [64]:
import pandas as pd
from glob import glob

In [65]:
files = glob("../data/raw/MetaMotion/*.csv")
data_path="../data/raw/MetaMotion/"

In [66]:
f = files[0]
f

'../data/raw/MetaMotion/E-dead-medium_MetaWear_2019-01-15T20.30.34.601_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv'

In [67]:
fs=f.split("-")
participents= fs[0].replace(data_path, "")
label= fs[1]
category= fs[2].rstrip("123").rstrip("_MetaWear_2019")

df=pd.read_csv(f)
df["participents"]=participents
df["label"]=label
df["category"]=category

df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participents,label,category
0,1547667034809,2019-01-16 20:30:34.809,0.00,4.207,-2.012,-0.305,E,dead,medium
1,1547667034849,2019-01-16 20:30:34.849,0.04,3.659,-2.317,0.305,E,dead,medium
2,1547667034889,2019-01-16 20:30:34.889,0.08,3.415,-1.890,1.341,E,dead,medium
3,1547667034929,2019-01-16 20:30:34.929,0.12,5.488,-3.415,2.988,E,dead,medium
4,1547667034969,2019-01-16 20:30:34.969,0.16,7.012,-7.927,3.049,E,dead,medium
...,...,...,...,...,...,...,...,...,...
869,1547667069569,2019-01-16 20:31:09.569,34.76,17.012,16.159,-10.244,E,dead,medium
870,1547667069609,2019-01-16 20:31:09.609,34.80,3.537,35.427,6.524,E,dead,medium
871,1547667069649,2019-01-16 20:31:09.649,34.84,-1.463,39.268,15.732,E,dead,medium
872,1547667069689,2019-01-16 20:31:09.689,34.88,0.305,24.085,14.451,E,dead,medium
873,1547667069729,2019-01-16 20:31:09.729,34.92,7.256,5.793,8.232,E,dead,medium

In [68]:
acs_df=pd.DataFrame()
gyro_df=pd.DataFrame()

acs_set=1
gyro_set=1

In [69]:
for f in files:
    fs=f.split("-")
    participents= fs[0].replace(data_path, "")
    label= fs[1]
    category= fs[2].rstrip("123").rstrip("_MetaWear_2019")
    
    df=pd.read_csv(f)

    df["participents"]=participents
    df["label"]=label
    df["category"]=category

    if "Accelerometer" in f:
        df["set"]=acs_set
        acs_set+=1
        acs_df=pd.concat([acs_df,df])

    if "Gyroscope" in f:
        df["set"]=gyro_set
        gyro_set+=1
        gyro_df=pd.concat([gyro_df,df])   

acs_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23578 entries, 0 to 185
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   epoch (ms)    23578 non-null  int64
 1   time (01:00)  23578 non-null  object
 2   elapsed (s)   23578 non-null  float64
 3   x-axis (g)    23578 non-null  float64
 4   y-axis (g)    23578 non-null  float64
 5   z-axis (g)    23578 non-null  float64
 6   participents  23578 non-null  object
 7   label         23578 non-null  object
 8   category      23578 non-null  object
 9   set           23578 non-null  int64
dtypes: float64(4), int64(2), object(4)
memory usage: 2.0+ MB

In [70]:
gyro_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47218 entries, 0 to 379
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   epoch (ms)      47218 non-null  int64
 1   time (01:00)    47218 non-null  object
 2   elapsed (s)     47218 non-null  float64
 3   x-axis (deg/s)  47218 non-null  float64
 4   y-axis (deg/s)  47218 non-null  float64
 5   z-axis (deg/s)  47218 non-null  float64
 6   participents    47218 non-null  object
 7   label           47218 non-null  object
 8   category        47218 non-null  object
 9   set             47218 non-null  int64
dtypes: float64(4), int64(2), object(4)
memory usage: 4.0+ MB

In [71]:
acs_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23578 entries, 0 to 185
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   epoch (ms)    23578 non-null  int64
 1   time (01:00)  23578 non-null  object
 2   elapsed (s)   23578 non-null  float64
 3   x-axis (g)    23578 non-null  float64
 4   y-axis (g)    23578 non-null  float64
 5   z-axis (g)    23578 non-null  float64
 6   participents  23578 non-null  object
 7   label         23578 non-null  object
 8   category      23578 non-null  object
 9   set           23578 non-null  int64
dtypes: float64(4), int64(2), object(4)
memory usage: 2.0+ MB

In [72]:
gyro_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47218 entries, 0 to 379
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   epoch (ms)      47218 non-null  int64
 1   time (01:00)    47218 non-null  object
 2   elapsed (s)     47218 non-null  float64
 3   x-axis (deg/s)  47218 non-null  float64
 4   y-axis (deg/s)  47218 non-null  float64
 5   z-axis (deg/s)  47218 non-null  float64
 6   participents    47218 non-null  object
 7   label           47218 non-null  object
 8   category        47218 non-null  object
 9   set             47218 non-null  int64
dtypes: float64(4), int64(2), object(4)
memory usage: 4.0+ MB

In [73]:
acs_df.index=pd.to_datetime(acs_df["epoch (ms)"],unit="ms")
gyro_df.index=pd.to_datetime(gyro_df["epoch (ms)"],unit="ms")


del acs_df["epoch (ms)"]
del acs_df["time (01:00)"]
del acs_df["elapsed (s)"]

del gyro_df["epoch (ms)"]
del gyro_df["time (01:00)"]
del gyro_df["elapsed (s)"]

In [74]:
gyro_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participents,label,category,set
epoch (ms),,,,,,,
2019-01-16 19:30:34.809,4.207,-2.012,-0.305,E,dead,medium,1
2019-01-16 19:30:34.849,3.659,-2.317,0.305,E,dead,medium,1
2019-01-16 19:30:34.889,3.415,-1.890,1.341,E,dead,medium,1
2019-01-16 19:30:34.929,5.488,-3.415,2.988,E,dead,medium,1
2019-01-16 19:30:34.969,7.012,-7.927,3.049,E,dead,medium,1
...,...,...,...,...,...,...,...
2019-01-14 13:53:21.457,-8.476,-0.915,-0.793,A,ohp,heavy,93
2019-01-14 13:53:21.497,-0.549,-3.780,-2.195,A,ohp,heavy,93
2019-01-14 13:53:21.537,1.829,-1.037,-0.427,A,ohp,heavy,93
2019-01-14 13:53:21.577,-3.963,2.500,-4.146,A,ohp,heavy,93
2019-01-14 13:53:21.617,0.183,1.890,-3.049,A,ohp,heavy,93

In [75]:
acs_df

,x-axis (g),y-axis (g),z-axis (g),participents,label,category,set
epoch (ms),,,,,,,
2019-01-11 15:12:05.287,0.031,0.974,0.026,B,bench,heavy,1
2019-01-11 15:12:05.367,0.034,0.986,0.021,B,bench,heavy,1
2019-01-11 15:12:05.447,0.000,0.927,0.018,B,bench,heavy,1
2019-01-11 15:12:05.527,0.004,0.780,-0.075,B,bench,heavy,1
2019-01-11 15:12:05.607,-0.027,0.701,-0.047,B,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-15 13:53:21.343,-0.060,0.976,-0.151,E,ohp,heavy,94
2019-01-15 13:53:21.423,-0.065,0.975,-0.121,E,ohp,heavy,94
2019-01-15 13:53:21.503,-0.056,0.979,-0.101,E,ohp,heavy,94
2019-01-15 13:53:21.583,-0.056,0.999,-0.087,E,ohp,heavy,94
2019-01-15 13:53:21.663,-0.049,0.968,-0.095,E,ohp,heavy,94

In [76]:

# Function
files1 = glob("../../data/raw/MetaMotion/*.csv")

def read_data_from_files(files):
    '''
    Read Raw date and convert into dataframe
    '''

    acs_df=pd.DataFrame()
    gyro_df=pd.DataFrame()

    acs_set=1
    gyro_set=1

    for f in files:

        fs=f.split("-")
        participents= fs[0].replace(data_path, "")
        label= fs[1]
        category= fs[2].rstrip("123").rstrip("_MetaWear_2019")
        
        df=pd.read_csv(f)

        df["participents"]=participents
        df["label"]=label
        df["category"]=category

        if "Accelerometer" in f:
            df["set"]=acs_set
            acs_set+=1
            acs_df=pd.concat([acs_df,df])

        if "Gyroscope" in f:
            df["set"]=gyro_set
            gyro_set+=1
            gyro_df=pd.concat([gyro_df,df])
        

    acs_df.index=pd.to_datetime(acs_df["epoch (ms)"],unit="ms")
    gyro_df.index=pd.to_datetime(gyro_df["epoch (ms)"],unit="ms")


    del acs_df["epoch (ms)"]
    del acs_df["time (01:00)"]
    del acs_df["elapsed (s)"]

    del gyro_df["epoch (ms)"]
    del gyro_df["time (01:00)"]
    del gyro_df["elapsed (s)"]

    return acs_df,gyro_df

In [77]:
data_marged=pd.concat([acs_df.iloc[:,:3],gyro_df],axis=1)

In [78]:
data_marged.columns=[
        "Accelerometer_x",
        "Accelerometer_y",
        "Accelerometer_z",
        "Gyroscope_x",
        "Gyroscope_y",
        "Gyroscope_z",
        "Participents",
        "Label",
        "Category",
        "Set"
]


sampling={
        "Accelerometer_x":"mean",
        "Accelerometer_y":"mean",
        "Accelerometer_z":"mean",
        "Gyroscope_x":"mean",
        "Gyroscope_y":"mean",
        "Gyroscope_z":"mean",
        "Participents":"last",
        "Label":"last",
        "Category":"last",
        "Set":"last"
}


data_marged[:1000].resample(rule="200ms").apply(sampling)

,Accelerometer_x,Accelerometer_y,Accelerometer_z,Gyroscope_x,Gyroscope_y,Gyroscope_z,Participents,Label,Category,Set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.800,NaN,NaN,NaN,-9.69550,-1.7985,4.5735,B,bench,heavy,30.0
2019-01-11 15:08:05.000,NaN,NaN,NaN,-2.01220,-0.4270,-1.6218,B,bench,heavy,30.0
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.89040,2.4392,0.9388,B,bench,heavy,30.0
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.68260,-0.8904,2.1708,B,bench,heavy,30.0
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.56080,-0.2560,-1.4146,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-11 15:10:21.600,-0.174000,1.092667,-0.153333,-4.96360,-16.4026,21.9026,A,bench,heavy,86.0
2019-01-11 15:10:21.800,-0.219500,1.402500,-0.109000,-7.52440,18.6706,-22.6828,A,bench,heavy,86.0
2019-01-11 15:10:22.000,-0.192000,0.871667,-0.155667,2.60980,8.7070,-14.8658,A,bench,heavy,86.0
2019-01-11 15:10:22.200,-0.227000,0.891000,-0.170000,5.39020,4.0000,-0.3780,A,bench,heavy,86.0
2019-01-11 15:10:22.400,-0.225500,0.919500,-0.205500,6.34125,0.5795,9.9085,A,bench,heavy,86.0

In [79]:
days=[g for a,g in data_marged.groupby(pd.Grouper(freq="D"))]
data_resampled=pd.concat([df.resample(rule="200ms").apply(sampling).dropna() for df in days])
data_resampled["Set"]=data_resampled["Set"].astype("int")

In [80]:
days[-1]

,Accelerometer_x,Accelerometer_y,Accelerometer_z,Gyroscope_x,Gyroscope_y,Gyroscope_z,Participents,Label,Category,Set
epoch (ms),,,,,,,,,,
2019-01-20 17:22:25.756,NaN,NaN,NaN,1.341,1.463,0.671,E,rest,sitting,89.0
2019-01-20 17:22:25.796,NaN,NaN,NaN,1.098,1.098,0.976,E,rest,sitting,89.0
2019-01-20 17:22:25.836,NaN,NaN,NaN,0.183,-2.195,0.305,E,rest,sitting,89.0
2019-01-20 17:22:25.876,NaN,NaN,NaN,0.061,-2.195,0.183,E,rest,sitting,89.0
2019-01-20 17:22:25.916,NaN,NaN,NaN,0.305,0.915,1.159,E,rest,sitting,89.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
data_resampled.to_pickle("../data/interim/01_Data_Processed.pkl")